version: '3.8'
services:
  atykym.space:
    restart: unless-stopped
    container_name: site
    image: ghcr.io/nyckyta/atykym.space:latest
    platform: linux/amd64
    networks:
      - site_network

  caddy:
    image: caddy:2.8
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "$WORKDIR/Caddyfile-prod:/etc/caddy/Caddyfile"
    networks:
      - site_network

networks:
  site_network:
