version: '3.8'
services:
  atykym.space:
    restart: unless-stopped
    container_name: site
    image: ghcr.io/nyckyta/atykym.space:latest
    user: app
    platform: linux/amd64
    ports:
      - '80:8080'
    environment:
      - PORT=8080
    networks:
      - site_network

networks:
  site_network:
    
