name: Application CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: go mod download && CGO_ENABLED=0 GOOS=linux go build -o /atykym.space && tar -c -a -f /atykym.space.tar.gz /atykym.space ./static/*
  
