name: Application CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
    - uses: actions/checkout@v3
    - name: Build the binary
      run: go mod download && CGO_ENABLED=0 GOOS=linux go build -buildvcs=false -o atykym.space
    - uses: actions/upload-artifact@v4
      with:
        path: atykym.space
        retention-days: 1
        overwrite: true

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        path: atykym.space
    - name: Package the app
      run: PORT=8080 docker build -t atykym.space:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
    - run: echo "BRRRRRRR..."
