name: Build workflow

on:
  workflow_call:


jobs:
  # build the binary
  build:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
    - uses: actions/checkout@v3
    - name: Build the binary
      run: go mod download && CGO_ENABLED=0 GOOS=linux go build -buildvcs=false -o atykym.space
    - uses: actions/upload-artifact@v4
      with:
        path: atykym.space
        name: atykym.space
        retention-days: 1
        overwrite: true
