name: Application CI/CD

on:
   push:
     branches: [ "master" ]

jobs:
  # build the binary
  build:
    uses: ./.github/workflows/build.yml
  # build the docker image
  package:
    needs: build
    uses: ./.github/workflows/package.yml
